# Generated by Django 5.1.5 on 2025-01-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_digital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(related_name='libros', to='Biblioteca_digital.categoria'),
        ),
    ]
