# Generated by Django 5.1.5 on 2025-01-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_digital', '0002_remove_libro_categoria_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(to='Biblioteca_digital.categoria'),
        ),
    ]
