# Generated by Django 5.1.5 on 2025-01-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_digital', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
